apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets
auth:
  secretStore: strongbox  
spec:
  type: bindings.twitter
  version: v1
  metadata:
  - name: consumerKey
    secretKeyRef:
      name: apiKey
  - name: consumerSecret
    secretKeyRef:
      name: apiKeySecret
  - name: accessToken
    secretKeyRef:
      name: accessToken
  - name: accessSecret
    secretKeyRef:
      name: accessTokenSecret
  - name: query
    value: "microsoft"